### ISSUE TITLE
Small fixes in `contract.py`

### ISSUE THREAD

**Issue by algochoi** [algorand-devrel/demo-abi#5]
Just noticed that `contract.py` might not compile on the latest Pyteal version due to:
1. the clear state program only accepts a `never()` or a `call_only()` -> `clear_state=OnCompleteAction.call_only(Approve()),`
2. In `min_bal()`, the `account`/`reference` type does not support the `get()` method anymore (originally inherited from `Uint`)

**Comment by barnjamin** [comment]
Good catch thanks!
